### PR TITLE
Fix for issue 9: Replaced complex generator logic with a deep flatten and chunk

### PR DESCRIPTION
**Pull request by dash-**
I'm something of an outsider, so I'm not 100% sure of what the getStates requirements were.  But looking at the logic and test cases, simply flattening the array and chunking (with size=2) should be preferable over a complex, recursive replacement.

Passes tests.  If this is not an adequate replacement, a more complex test should be devised showing more full range of acceptable input/output.

David Ash (tw: netjumpio)

### CODE REVIEW

**Comment by ericelliott** [comment]
Flattening the array is good thinking but it's also a lossy opperation, meaning that we'll lose the information about which transitions are allowed in which states. That feature has not been implemented yet. I was thinking of automatically creating a new reducer for each state with valid transitions.

Do you have thoughts on that?

**Comment by dash-** [comment]
Okay, that makes sense.  A recursive method will be needed, unless you had a different clever idea in mind.

**Comment by dash-** [comment]
I'm pushing a recursive solution on a different branch.  Pretty sure it would be forward compatible with the feature you described.

**Comment by dash-** [comment]
https://github.com/ericelliott/redux-dsm/pull/12

**Pull request closed without merging**
